[package]
name = "vg_usb_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.2.0"
fltk = "1.5.0"
fltk-theme = "0.7.3"
posix = "0.0.2"
serialport = "4.6.1"

[[bin1]]
name = "vg-usb-interface_linux"

[[bin2]]
name = "vg-usb-interface_windows"
